language: objective-c
before_install:
    - gem install xctest-runner
    - gem install xcpretty
script:
    - xcodebuild -workspace NSDictionaryAsURkLQuery.xcworkspace -scheme NSDictionaryAsURLQueryTests -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' test | xcpretty -c